
import { Team } from './types';

export const INITIAL_TEAMS: Team[] = [
  { id: 1, name: 'Thunder', logo: 'https://a.espncdn.com/i/teamlogos/nba/500/okc.png', record: ['V', 'D', 'D', 'V', 'V'], wins: 45, losses: 18, conference: 'West' },
  { id: 2, name: 'Pistons', logo: 'https://a.espncdn.com/i/teamlogos/nba/500/det.png', record: ['D', 'V', 'V', 'V', 'D'], wins: 12, losses: 51, conference: 'East' },
  { id: 3, name: 'Spurs', logo: 'https://a.espncdn.com/i/teamlogos/nba/500/sas.png', record: ['V', 'D', 'D', 'V', 'V'], wins: 14, losses: 50, conference: 'West' },
  { id: 4, name: 'Nuggets', logo: 'https://a.espncdn.com/i/teamlogos/nba/500/den.png', record: ['D', 'D', 'V', 'V', 'D'], wins: 44, losses: 20, conference: 'West' },
  { id: 5, name: 'Timberwolves', logo: 'https://a.espncdn.com/i/teamlogos/nba/500/min.png', record: ['V', 'V', 'V', 'V', 'D'], wins: 44, losses: 19, conference: 'West' },
  { id: 6, name: 'Lakers', logo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png', record: ['V', 'V', 'V', 'D', 'D'], wins: 34, losses: 30, conference: 'West' },
  { id: 7, name: 'Celtics', logo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png', record: ['V', 'V', 'D', 'V', 'D'], wins: 48, losses: 14, conference: 'East' },
  { id: 8, name: 'Knicks', logo: 'https://a.espncdn.com/i/teamlogos/nba/500/nyk.png', record: ['D', 'D', 'D', 'V', 'D'], wins: 36, losses: 27, conference: 'East' },
  { id: 9, name: 'Rockets', logo: 'https://a.espncdn.com/i/teamlogos/nba/500/hou.png', record: ['V', 'D', 'V', 'D', 'D'], wins: 27, losses: 35, conference: 'West' },
  { id: 10, name: 'Suns', logo: 'https://a.espncdn.com/i/teamlogos/nba/500/phx.png', record: ['V', 'V', 'D', 'V', 'V'], wins: 37, losses: 26, conference: 'West' },
  { id: 11, name: 'Raptors', logo: 'https://a.espncdn.com/i/teamlogos/nba/500/tor.png', record: ['D', 'V', 'V', 'V', 'D'], wins: 23, losses: 40, conference: 'East' },
  { id: 12, name: '76ers', logo: 'https://a.espncdn.com/i/teamlogos/nba/500/phi.png', record: ['V', 'V', 'D', 'V', 'V'], wins: 35, losses: 28, conference: 'East' },
  { id: 13, name: 'Cavaliers', logo: 'https://a.espncdn.com/i/teamlogos/nba/500/cle.png', record: ['V', 'D', 'V', 'D', 'V'], wins: 40, losses: 22, conference: 'East' },
  { id: 14, name: 'Warriors', logo: 'https://a.espncdn.com/i/teamlogos/nba/500/gsw.png', record: ['D', 'V', 'D', 'V', 'V'], wins: 33, losses: 29, conference: 'West' },
  { id: 15, name: 'Magic', logo: 'https://a.espncdn.com/i/teamlogos/nba/500/orl.png', record: ['D', 'V', 'D', 'V', 'D'], wins: 37, losses: 26, conference: 'East' },
  { id: 16, name: 'Heat', logo: 'https://a.espncdn.com/i/teamlogos/nba/500/mia.png', record: ['V', 'D', 'V', 'D', 'D'], wins: 35, losses: 28, conference: 'East' },
  { id: 17, name: 'Trail Blazers', logo: 'https://a.espncdn.com/i/teamlogos/nba/500/por.png', record: ['V', 'V', 'V', 'V', 'V'], wins: 17, losses: 45, conference: 'West' },
  { id: 18, name: 'Hawks', logo: 'https://a.espncdn.com/i/teamlogos/nba/500/atl.png', record: ['V', 'D', 'D', 'V', 'V'], wins: 28, losses: 34, conference: 'East' },
  { id: 19, name: 'Bulls', logo: 'https://a.espncdn.com/i/teamlogos/nba/500/chi.png', record: ['V', 'D', 'D', 'D', 'V'], wins: 30, losses: 33, conference: 'East' },
  { id: 20, name: 'Bucks', logo: 'https://a.espncdn.com/i/teamlogos/nba/500/mil.png', record: ['D', 'V', 'V', 'D', 'V'], wins: 41, losses: 22, conference: 'East' },
  { id: 21, name: 'Grizzlies', logo: 'https://a.espncdn.com/i/teamlogos/nba/500/mem.png', record: ['D', 'D', 'V', 'D', 'D'], wins: 22, losses: 41, conference: 'West' },
  { id: 22, name: 'Clippers', logo: 'https://a.espncdn.com/i/teamlogos/nba/500/lac.png', record: ['D', 'V', 'D', 'V', 'V'], wins: 50, losses: 14, conference: 'West' },
  { id: 23, name: 'Hornets', logo: 'https://a.espncdn.com/i/teamlogos/nba/500/cha.png', record: ['V', 'V', 'D', 'D', 'V'], wins: 15, losses: 48, conference: 'East' },
  { id: 24, name: 'Mavericks', logo: 'https://a.espncdn.com/i/teamlogos/nba/500/dal.png', record: ['D', 'V', 'V', 'D', 'D'], wins: 35, losses: 28, conference: 'West' },
  { id: 25, name: 'Jazz', logo: 'https://a.espncdn.com/i/teamlogos/nba/500/utah.png', record: ['D', 'D', 'D', 'V', 'D'], wins: 28, losses: 35, conference: 'West' },
  { id: 26, name: 'Nets', logo: 'https://a.espncdn.com/i/teamlogos/nba/500/bkn.png', record: ['D', 'D', 'V', 'D', 'D'], wins: 25, losses: 38, conference: 'East' },
  { id: 27, name: 'Wizards', logo: 'https://a.espncdn.com/i/teamlogos/nba/500/was.png', record: ['V', 'D', 'V', 'D', 'D'], wins: 10, losses: 53, conference: 'East' },
  { id: 28, name: 'Pelicans', logo: 'https://a.espncdn.com/i/teamlogos/nba/500/no.png', record: ['D', 'D', 'D', 'D', 'V'], wins: 38, losses: 25, conference: 'West' },
  { id: 29, name: 'Kings', logo: 'https://a.espncdn.com/i/teamlogos/nba/500/sac.png', record: ['D', 'D', 'D', 'D', 'D'], wins: 35, losses: 26, conference: 'West' },
  { id: 30, name: 'Pacers', logo: 'https://a.espncdn.com/i/teamlogos/nba/500/ind.png', record: ['D', 'D', 'D', 'V', 'V'], wins: 35, losses: 29, conference: 'East' },
];

export const INITIAL_ESPN_DATA = [
  { time: 'Clippers', vitorias: 50, derrotas: 14, ultimos_5: 'W4', media_pontos_ataque: 118.5, media_pontos_defesa: 108.2, aproveitamento: 0.781 },
  { time: 'Celtics', vitorias: 48, derrotas: 14, ultimos_5: 'V-V-D-V-D', media_pontos_ataque: 120.5, media_pontos_defesa: 110.2, aproveitamento: 0.774 },
  { time: 'Thunder', vitorias: 45, derrotas: 18, ultimos_5: 'V-D-D-V-V', media_pontos_ataque: 121.0, media_pontos_defesa: 113.5, aproveitamento: 0.714 },
  { time: 'Timberwolves', vitorias: 44, derrotas: 19, ultimos_5: 'V-V-V-V-D', media_pontos_ataque: 115.2, media_pontos_defesa: 106.8, aproveitamento: 0.698 },
  { time: 'Nuggets', vitorias: 44, derrotas: 20, ultimos_5: 'D-D-V-V-D', media_pontos_ataque: 114.8, media_pontos_defesa: 111.0, aproveitamento: 0.688 },
  { time: 'Bucks', vitorias: 41, derrotas: 22, ultimos_5: 'D-V-V-D-V', media_pontos_ataque: 121.5, media_pontos_defesa: 117.2, aproveitamento: 0.651 },
  { time: 'Cavaliers', vitorias: 40, derrotas: 22, ultimos_5: 'V-D-V-D-V', media_pontos_ataque: 114.3, media_pontos_defesa: 109.5, aproveitamento: 0.645 },
  { time: 'Pelicans', vitorias: 38, derrotas: 25, ultimos_5: 'D-D-D-D-V', media_pontos_ataque: 116.1, media_pontos_defesa: 111.8, aproveitamento: 0.603 },
  { time: 'Suns', vitorias: 37, derrotas: 26, ultimos_5: 'V-V-D-V-V', media_pontos_ataque: 117.1, media_pontos_defesa: 114.3, aproveitamento: 0.587 },
  { time: 'Magic', vitorias: 37, derrotas: 26, ultimos_5: 'D-V-D-V-D', media_pontos_ataque: 110.8, media_pontos_defesa: 109.4, aproveitamento: 0.587 },
  { time: 'Knicks', vitorias: 36, derrotas: 27, ultimos_5: 'D-D-D-V-D', media_pontos_ataque: 113.5, media_pontos_defesa: 113.1, aproveitamento: 0.571 },
  { time: 'Heat', vitorias: 35, derrotas: 28, ultimos_5: 'V-D-V-D-D', media_pontos_ataque: 110.5, media_pontos_defesa: 109.8, aproveitamento: 0.556 },
  { time: '76ers', vitorias: 35, derrotas: 28, ultimos_5: 'V-V-D-V-V', media_pontos_ataque: 116.5, media_pontos_defesa: 113.8, aproveitamento: 0.556 },
  { time: 'Kings', vitorias: 35, derrotas: 26, ultimos_5: 'D-D-D-D-D', media_pontos_ataque: 118.1, media_pontos_defesa: 117.5, aproveitamento: 0.574 },
  { time: 'Pacers', vitorias: 35, derrotas: 29, ultimos_5: 'D-D-D-V-V', media_pontos_ataque: 123.5, media_pontos_defesa: 121.8, aproveitamento: 0.547 },
  { time: 'Mavericks', vitorias: 35, derrotas: 28, ultimos_5: 'D-V-V-D-D', media_pontos_ataque: 118.7, media_pontos_defesa: 118.0, aproveitamento: 0.556 },
  { time: 'Lakers', vitorias: 34, derrotas: 30, ultimos_5: 'V-V-V-D-D', media_pontos_ataque: 117.2, media_pontos_defesa: 117.6, aproveitamento: 0.531 },
  { time: 'Warriors', vitorias: 33, derrotas: 29, ultimos_5: 'D-V-D-V-V', media_pontos_ataque: 118.9, media_pontos_defesa: 117.2, aproveitamento: 0.532 },
  { time: 'Bulls', vitorias: 30, derrotas: 33, ultimos_5: 'V-D-D-D-V', media_pontos_ataque: 111.7, media_pontos_defesa: 113.5, aproveitamento: 0.476 },
  { time: 'Hawks', vitorias: 28, derrotas: 34, ultimos_5: 'V-D-D-V-V', media_pontos_ataque: 120.2, media_pontos_defesa: 122.1, aproveitamento: 0.452 },
  { time: 'Jazz', vitorias: 28, derrotas: 35, ultimos_5: 'D-D-D-V-D', media_pontos_ataque: 117.4, media_pontos_defesa: 120.5, aproveitamento: 0.444 },
  { time: 'Rockets', vitorias: 27, derrotas: 35, ultimos_5: 'V-D-V-D-D', media_pontos_ataque: 112.8, media_pontos_defesa: 113.2, aproveitamento: 0.435 },
  { time: 'Nets', vitorias: 25, derrotas: 38, ultimos_5: 'D-D-V-D-D', media_pontos_ataque: 112.2, media_pontos_defesa: 114.5, aproveitamento: 0.397 },
  { time: 'Raptors', vitorias: 23, derrotas: 40, ultimos_5: 'D-V-V-V-D', media_pontos_ataque: 114.1, media_pontos_defesa: 118.2, aproveitamento: 0.365 },
  { time: 'Grizzlies', vitorias: 22, derrotas: 41, ultimos_5: 'D-D-V-D-D', media_pontos_ataque: 106.1, media_pontos_defesa: 112.5, aproveitamento: 0.349 },
  { time: 'Trail Blazers', vitorias: 17, derrotas: 45, ultimos_5: 'V-V-V-V-V', media_pontos_ataque: 107.8, media_pontos_defesa: 116.1, aproveitamento: 0.274 },
  { time: 'Hornets', vitorias: 15, derrotas: 48, ultimos_5: 'V-V-D-D-V', media_pontos_ataque: 107.5, media_pontos_defesa: 117.8, aproveitamento: 0.238 },
  { time: 'Spurs', vitorias: 14, derrotas: 50, ultimos_5: 'V-D-D-V-V', media_pontos_ataque: 112.5, media_pontos_defesa: 120.1, aproveitamento: 0.219 },
  { time: 'Pistons', vitorias: 12, derrotas: 51, ultimos_5: 'D-V-V-V-D', media_pontos_ataque: 112.1, media_pontos_defesa: 121.0, aproveitamento: 0.190 },
  { time: 'Wizards', vitorias: 10, derrotas: 53, ultimos_5: 'V-D-V-D-D', media_pontos_ataque: 114.5, media_pontos_defesa: 124.2, aproveitamento: 0.159 }
];
